/**
 *
 * @author Zacheriah Mell
 */
package views;

import javax.swing.JButton;
import javax.swing.JTextField;

public class AddCircDialog extends javax.swing.JDialog {
    
  public JTextField getDiamterField() {
    return diameter;
  }
  
  public JTextField getStrokeWidthField() {
    return strokeWidth;
  }
  
  public JTextField getLineColorField() {
    return lineColor;
  }
  
  public JTextField getFillColorField() {
    return fillColor;
  }
  
  public JTextField getTitleField() {
    return title;
  }
  
  public JButton getAddButton() {
    return add;
  }
  
  public JButton getCancelButton() {
    return cancel;
  }
  
  public JButton getChooseLineColor() {
    return chooseLineColor;
  }
  
  public JButton getChooseFillColor() {
    return chooseFillColor;
  }

  /**
   * Creates new form AddRectDialog
   */
  public AddCircDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    //width = new javax.swing.JTextField();
    diameter = new javax.swing.JTextField();
    strokeWidth = new javax.swing.JTextField();
    lineColor = new javax.swing.JTextField();
    fillColor = new javax.swing.JTextField();
    title = new javax.swing.JTextField();
    add = new javax.swing.JButton();
    chooseLineColor = new javax.swing.JButton();
    chooseFillColor = new javax.swing.JButton();
    cancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setText("");

    jLabel2.setText("Diamter:");

    jLabel3.setText("line color:");

    jLabel4.setText("fill color:");

    jLabel5.setText("title:");

    jLabel6.setText("stroke width:");

    diameter.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        heightActionPerformed(evt);
      }
    });

    lineColor.setEditable(false);
    lineColor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lineColorActionPerformed(evt);
      }
    });

    fillColor.setEditable(false);

    add.setText("Add");
    add.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addActionPerformed(evt);
      }
    });

    chooseLineColor.setText("Choose");
    chooseLineColor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chooseLineColorActionPerformed(evt);
      }
    });

    chooseFillColor.setText("Choose");

    cancel.setText("Cancel");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel2))
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(diameter, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
            ))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel3)
              .addComponent(jLabel6)
              .addComponent(jLabel4)
              .addComponent(jLabel5))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(strokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(lineColor, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                  .addComponent(fillColor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(chooseLineColor)
                  .addComponent(chooseFillColor)))
              .addGroup(layout.createSequentialGroup()
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel)))))
        .addContainerGap(55, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          )
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(diameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel6)
            .addComponent(strokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lineColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(chooseLineColor))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(fillColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(chooseFillColor))
        .addGap(16, 16, 16)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(add)
          .addComponent(cancel))
        .addContainerGap(26, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>                        

  private void addActionPerformed(java.awt.event.ActionEvent evt) {                                    
    // TODO add your handling code here:
  }                                   

  private void heightActionPerformed(java.awt.event.ActionEvent evt) {                                       
    // TODO add your handling code here:
  }                                      

  private void lineColorActionPerformed(java.awt.event.ActionEvent evt) {                                          
    // TODO add your handling code here:
  }                                         

  private void chooseLineColorActionPerformed(java.awt.event.ActionEvent evt) {                                                
    // TODO add your handling code here:
  }                                               

  // Variables declaration - do not modify                     
  private javax.swing.JButton add;
  private javax.swing.JButton cancel;
  private javax.swing.JButton chooseFillColor;
  private javax.swing.JButton chooseLineColor;
  private javax.swing.JTextField fillColor;
  private javax.swing.JTextField diameter;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JTextField lineColor;
  private javax.swing.JTextField strokeWidth;
  private javax.swing.JTextField title;
  // End of variables declaration                   
}
